name: librarying
dependencies:
  validator: ">=0.0.4 <0.1.0"
  test: "^0.12.4+4"
  redis_client: any
  rpc: "^0.5.2"
  sqljocky: "^0.13.0"
  uuid: 0.5.0
  WAGEncryption:
      git:
        url: git://github.com/SecareLupus/WAGEncryption.git
        ref: master